[scopes]
deps = ["go.sum", "go.mod"]
cli = ["src", "package.json", "app/commands"]
api = ["api/dex", "api/did", "api/dwn", "api/svc", "api"]
ante = ["app/ante"]
app = ["app/context", "app/decorators", "app/params", "app/upgrades", "app"]
chains = ["chains"]
cmd = ["cmd/snrd", "cmd"]
docs = ["docs"]
config = ["networks/localnet", "networks/testnet", "networks"]
dex = ["proto/dex", "x/dex"]
did = ["proto/did", "x/did"]
dwn = ["proto/dwn", "x/dwn"]
svc = ["proto/svc", "x/svc"]
proto = ["proto"]
scripts = ["scripts"]
test = ["test/e2e", "test/integration", "test/oauth", "test"]
ci = ["Makefile", ".github"]
