[scopes]
deps = ["go.sum", "go.mod", "package.json", "bun.lock", "pnpm-lock.yaml"]
techdocs = ["docs"]
actions = [".github/workflows"]
config = [".github", "networks/localnet", "networks/testnet", "networks", "devbox.json", "devbox.lock", "docker-compose.yml", "wrangler.toml"]
cli = ["src", "app/commands", "cmd/sonrctl"]
cmd = ["cmd/snrd", "cmd"]
app = ["app/context", "app/decorators", "app/params", "app/upgrades", "app"]
ante = ["app/ante"]
api = ["api/dex", "api/did", "api/dwn", "api/svc", "api"]
proto = ["proto/dex", "proto/did", "proto/dwn", "proto/svc", "proto"]
dex = ["x/dex"]
did = ["x/did"]
dwn = ["x/dwn"]
svc = ["x/svc"]
chains = ["chains"]
scripts = ["scripts"]
test = ["test/e2e", "test/integration", "test/oauth", "test"]
build = ["Makefile"]
