[scopes]
ante = ["app/ante"]
api = ["api/dex", "api/did", "api/dwn", "api/svc", "api"]
app = ["app/context", "app/decorators", "app/params", "app/upgrades", "app"]
chains = ["chains"]
ci = ["Makefile", ".github"]
cli = ["app/commands"]
cmd = ["cmd/snrd", "cmd"]
config = ["networks/localnet", "networks/testnet", "networks"]
deps = ["go.sum", "go.mod"]
dex = ["proto/dex", "x/dex"]
did = ["proto/did", "x/did"]
docs = ["docs"]
dwn = ["proto/dwn", "x/dwn"]
proto = ["proto"]
scripts = ["scripts"]
svc = ["proto/svc", "x/svc"]
test = ["test/e2e", "test/integration", "test/oauth", "test"]
